name: Build Pickish Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Create spec file if not exists
      run: |
        if (-not (Test-Path "pickish.spec")) {
          Write-Host "Creating pickish.spec file..."
          python -m PyInstaller --name Pickish --onefile --windowed --hidden-import PIL._tkinter_finder photo_filter_enhanced.py
          Move-Item "Pickish.spec" "pickish.spec" -Force
        }
        
    - name: Build executable
      run: |
        python -m PyInstaller pickish.spec --clean
        
    - name: Create distribution package
      run: |
        if (-not (Test-Path "Pickish_Distribution")) {
          New-Item -ItemType Directory -Path "Pickish_Distribution" | Out-Null
        }
        Copy-Item "dist\\Pickish.exe" "Pickish_Distribution\\"
        Copy-Item "README.md" "Pickish_Distribution\\README.md"
        Copy-Item "VERSION_HISTORY.md" "Pickish_Distribution\\"
        Copy-Item "run_pickish.bat" "Pickish_Distribution\\"
        
    - name: Create ZIP archive
      run: |
        powershell Compress-Archive -Path "Pickish_Distribution\*" -DestinationPath "Pickish_v${{ github.run_number }}.zip" -Force
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Pickish-Executable
        path: |
          dist/Pickish.exe
          Pickish_v${{ github.run_number }}.zip
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Pickish_v${{ github.run_number }}.zip
        body: |
          ## Pickish v${{ github.ref_name }}
          
          ### What's New
          - Automated build from GitHub Actions
          - Standalone executable for Windows
          - No Python installation required
          
          ### Installation
          1. Download the ZIP file
          2. Extract to any folder
          3. Run `Pickish.exe` or `run_pickish.bat`
          
          ### Features
          - Three-category photo filtering (Love, Like, Dislike)
          - Keyboard shortcuts for fast filtering
          - Undo support for all actions
          - Auto-rotation for vertical images
          - Background processing for smooth performance
          
          See README.md for detailed instructions.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 