name: Release Pickish Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        python -m PyInstaller pickish.spec --clean
        
    - name: Release Pickish.exe
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Pickish.exe
        body: |
          Pickish ${{ github.ref_name }} release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 