name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Create spec file if not exists
      run: |
        if (-not (Test-Path "pickish.spec")) {
          Write-Host "Creating pickish.spec file..."
          python -m PyInstaller --name Pickish --onefile --windowed --hidden-import PIL._tkinter_finder photo_filter_enhanced.py
          Move-Item "Pickish.spec" "pickish.spec" -Force
        }
        
    - name: Build executable
      run: |
        python -m PyInstaller pickish.spec --clean
        
    - name: Create distribution package
      run: |
        if (-not (Test-Path "Pickish_Distribution")) {
          New-Item -ItemType Directory -Path "Pickish_Distribution" | Out-Null
        }
        Copy-Item "dist\\Pickish.exe" "Pickish_Distribution\\"
        Copy-Item "README.md" "Pickish_Distribution\\README.md"
        Copy-Item "VERSION_HISTORY.md" "Pickish_Distribution\\"
        Copy-Item "run_pickish.bat" "Pickish_Distribution\\"
        
    - name: Create ZIP archive
      run: |
        $version = "${{ github.ref_name }}"
        $version = $version.TrimStart('v')
        $zipName = "Pickish_v$version.zip"
        Write-Host "Creating ZIP file: $zipName"
        Compress-Archive -Path "Pickish_Distribution\*" -DestinationPath $zipName -Force
        
    - name: Create Release
      run: |
        $version = "${{ github.ref_name }}"
        $version = $version.TrimStart('v')
        $zipName = "Pickish_v$version.zip"
        
        Write-Host "Creating GitHub release for $version"
        Write-Host "ZIP file: $zipName"
        
        # Create release using GitHub CLI
        gh release create $version --title "Pickish $version" --notes "Pickish $version release" $zipName
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }} 