name: Test Build

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Syntax check
      run: |
        python -c "import photo_filter_enhanced; print('Syntax check passed')"
        
    - name: Test build (dry run)
      run: |
        python -m PyInstaller --dry-run pickish.spec
        
    - name: Check file structure
      run: |
        echo "Checking required files exist..."
        if not exist "photo_filter_enhanced.py" exit 1
        if not exist "requirements.txt" exit 1
        if not exist "README.md" exit 1
        if not exist "VERSION_HISTORY.md" exit 1
        echo "All required files found!"
        
    - name: Validate version
      run: |
        python -c "
        import photo_filter_enhanced
        version = photo_filter_enhanced.PhotoFilterApp.VERSION
        print(f'Version: {version}')
        if not version or version == '0.0.0':
            exit(1)
        print('Version validation passed')
        " 